/******************************************************************************
** (C) Chris Wood 1995
**
** HELPIDS.H - HelpText IDs.
**
******************************************************************************* 
*/

/* IDs for each section. */
#define IDH_FILESERVER   0
#define IDH_QUEUES       1
#define IDH_JOBLIST      2
#define IDH_JOBINFO      3
#define IDH_PRINTSERVER  4
#define IDH_PSINFO       5
