/******************************************************************************
** (C) Chris Wood 1995
**
** HELPIDS.H - HelpText IDs.
**
******************************************************************************* 
*/

/* IDs for each section. */
#define IDH_LPTPORT      0
#define IDH_LPTDIALOG    1
#define IDH_QUEUENAME    2
#define IDH_FORMNAME     3
#define IDH_SHOWTABS     4
#define IDH_SHOWBANNER   5
#define IDH_FORMFEED     6
