/******************************************************************************
** (C) Chris Wood 1994/95.
**
** NWGERR.H - Error return codes.
**
******************************************************************************* 
*/

/* First check for previous inclusion. */
#ifndef _NWGERR_H
#define _NWGERR_H

#define NWGERR_NONE      0         /* No error occurred. */
#define NWGERR_ALLOC     -1        /* Memory allocation failed. */
#define NWGERR_VIDEO     -2        /* Unsupported video mode. */    

/* _NWGERR_H */
#endif
