/******************************************************************************
** (C) Chris Wood 1994/95.
**
** NWGFX.H - Main header file used in the application.
**
******************************************************************************* 
*/

/* First check for previous inclusion. */
#ifndef _NWGFX_H
#define _NWGFX_H

/* Include all other headers except NWGPRIV.H. */
#include "nwgtypes.h"
#include "nwghelp.h"
#include "nwgmenu.h"
#include "nwgdlg.h"
#include "nwgframe.h"
#include "nwgerr.h"
#include "nwgstyle.h"
#include "nwgcodes.h"
#include "nwgproto.h"

/* _NWGFX_H */
#endif
